"""Notification severity, category, and event type constants."""

SEVERITY_INFO = "INFO"
SEVERITY_WARNING = "WARNING"
SEVERITY_ERROR = "ERROR"
VALID_SEVERITIES = {SEVERITY_INFO, SEVERITY_WARNING, SEVERITY_ERROR}

CAT_DISPATCHER = "DISPATCHER"
CAT_INGESTION = "INGESTION"
CAT_CONFIG = "CONFIG"
CAT_SCHEMA = "SCHEMA"
CAT_PARSE = "PARSE"
VALID_CATEGORIES = {CAT_DISPATCHER, CAT_INGESTION, CAT_CONFIG, CAT_SCHEMA, CAT_PARSE}

EVT_DUPLICATE_CONFIG_RESOLVED = "DUPLICATE_CONFIG_RESOLVED"
EVT_EMPTY_CONFIG = "EMPTY_CONFIG"
EVT_NO_ELIGIBLE_FILES = "NO_ELIGIBLE_FILES"
EVT_SCHEMA_DRIFT_DETECTED = "SCHEMA_DRIFT_DETECTED"
EVT_SCHEMA_SEED_MISSING = "SCHEMA_SEED_MISSING"
EVT_PARSE_FAILED = "PARSE_FAILED"
EVT_TRIGGER_FAILED = "TRIGGER_FAILED"
EVT_TRIGGER_SKIPPED = "TRIGGER_SKIPPED"
EVT_JOB_RESOLVE_FAILED = "JOB_RESOLVE_FAILED"
EVT_AUTO_TRIGGER_DISABLED = "AUTO_TRIGGER_DISABLED"
EVT_ACTIVE_RUN_GUARD = "ACTIVE_RUN_GUARD"
EVT_ENV_POLICY_VIOLATION = "ENV_POLICY_VIOLATION"
